### ISSUE TITLE
Clang no more supported

### ISSUE THREAD

**Issue by alessandro308** [phvu/cuda-smi#4]
```
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be 
removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('90000') of the host compiler ('Apple clang') is not supported
```

**Comment by webcpu** [comment]
You can build cuda-smi if you install old command line tool for Xcode 8.3.2, however cuda-smi doesn't work in High Sierra.
<img width="758" alt="screen shot 2017-11-18 at 15 52 01" src="https://user-images.githubusercontent.com/4646838/32981641-87f9157c-cc78-11e7-8dc9-eb807a187af4.png">


## How to do it?
- Download and install Command Line Tool for 8.3.2 from https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_8.3.2/CommandLineToolsforXcode8.3.2.dmg
- Run 'sudo xcode-select --switch /Library/Developer/CommandLineTools'
- Test clang --version:
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

If you want to reset command line tools,
- Run 'sudo xcode-select --reset'

**Comment by micahstubbs** [comment]
worked for me, thanks @unchartedworks 🙏 

![screen shot 2017-11-21 at 1 07 15 pm](https://user-images.githubusercontent.com/2119400/33097309-9048ca04-cebe-11e7-9353-7a62876c86dd.png)
