### ISSUE TITLE
make a release with the binary

### ISSUE THREAD

**Issue by micahstubbs** [phvu/cuda-smi#5]
hi @phvu 👋 

it would be nice to make a release that contains the binary, to remove the build requirement (since the build fails for people with `Apple LLVM version 9.0.0 (clang-900.0.38)` https://github.com/phvu/cuda-smi/issues/4

I've made a release on my fork https://github.com/micahstubbs/cuda-smi/releases/tag/v1.0

but of course it would be nice to have a release your main **cuda-smi** [repo](https://github.com/phvu/cuda-smi) 😄

**Comment by phvu** [comment]
Thanks @micahstubbs, I added a sentence into README pointing to your release.
New MacBook doesn't ship with nVidia GPU anymore, I don't think this is in high demand.
